### ISSUE TITLE
Can't progress past Unlocking Jenkins.

### ISSUE THREAD

**Issue by dapperfu** [freenas/iocage-plugin-jenkins#1]
Jenkins setup with:

    iocage fetch -P --name /mnt/keg/projects/iocage-ix-plugins/jenkins.json ip4_addr="igb0|172.16.0.80"

Jenkins appropriately shows up at http://172.16.0.80/jenkins/

Where you get the 'unlock' screen.

```
Unlock Jenkins
To ensure Jenkins is securely set up by the administrator, a password has been written to the log (not sure where to find it?) and this file on the server:

/usr/local/jenkins/secrets/initialAdminPassword

Please copy the password from either location and paste it below.
```

Get the initialAdminPassword from ```jls```.

```
    15  172.16.0.80     jenkins                       /mnt/iocage/jails/jenkins/root
nas# jexec 15 cat /usr/local/jenkins/secrets/initialAdminPassword
hunter2
nas#
```

However entering the password redirects you to: http://localhost/jenkins/

During nginx/jenkins setup the hostname probably needs to be setup to the static IP.

**Comment by alhirzel** [comment]
Still an issue out-of-the-box with Jenkins as distributed with BETA3.

**Comment by MiwiDots** [comment]
Hi @jed-frey @alhirzel,

First of all sorry for the late respond I did miss the comment here, I have patched the plugin to fix the issue, please give it a try and let us know. Thanks!

**Comment by alhirzel** [comment]
@miwi-fbsd, no apologies needed, thank you for your promptness and time! I manually applied your change and it works great. My work-around was to set something closer to a FQDN, but your solution is much better/more general.

**Comment by MiwiDots** [comment]
Glade to hear that :).
